"""init

Revision ID: da3b8e84ec49
Revises: 
Create Date: 2022-01-17 11:19:12.523209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da3b8e84ec49'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=35), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_table('terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_eng', sa.String(length=100), nullable=False),
    sa.Column('name_rus', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category'], ['categories.id'], name='fk_terms_categories_id_category'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_eng', 'name_rus', 'category', name='uc_terms_name_eng_name_rus_category')
    )
    op.create_index(op.f('ix_terms_name_eng'), 'terms', ['name_eng'], unique=False)
    op.create_index(op.f('ix_terms_name_rus'), 'terms', ['name_rus'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_terms_name_rus'), table_name='terms')
    op.drop_index(op.f('ix_terms_name_eng'), table_name='terms')
    op.drop_table('terms')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
